-- 创建 app_data 表用于存储用户数据
CREATE TABLE IF NOT EXISTS app_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT 'default_user',
  key TEXT NOT NULL,
  value TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
  UNIQUE(user_id, key)
);

-- 创建索引以优化查询
CREATE INDEX IF NOT EXISTS idx_app_data_user_key ON app_data(user_id, key);
CREATE INDEX IF NOT EXISTS idx_app_data_key ON app_data(key);

-- 创建更新时间触发器
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = TIMEZONE('utc', NOW());
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_app_data_updated_at BEFORE UPDATE
ON app_data FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 启用行级安全 (RLS)
ALTER TABLE app_data ENABLE ROW LEVEL SECURITY;

-- 创建允许所有用户读写自己数据的策略
CREATE POLICY "Users can manage their own data" ON app_data
  FOR ALL
  USING (user_id = 'default_user')
  WITH CHECK (user_id = 'default_user');